### ISSUE TITLE
Create a home page

### ISSUE THREAD

**Issue by oiricaud** [evestore/planning#1]
A user should be able to navigate to `http://localhost:4200` and view a home page.

**Set up your local environment**
- [x] 1) Install [homebrew](https://brew.sh/) cli on your machine
- [x] 2) Install [Node](https://nodejs.org/en/) cli on your machine
- [x] 3) Install [Angular](https://cli.angular.io/) CLI on your machine
- [x] 4) Install [iTerm2](https://www.iterm2.com/) and use it instead of terminal
- [x] 5) Install `zsh` on your iTerm2 https://github.com/ohmyzsh/ohmyzsh/wiki/Installing-ZSH

**Tasks**
- [ ] 1) Create a new branch called `ticket-1` and push your code on https://github.com/evestore/evestore-web
- [x] 2) Build and deploy hello world in angular more info [here](https://angular.io/start)
- [ ] 3) Make changes to the default angular template 
- [ ] 4) Compile angular application by running `ng serve`

**Success Criteria**
- [ ] The code compiles
- [ ] At least 1 test case 
- [ ] The user is able to view the home page on`http:/localhost:4200`

**Resources**
Angular Documentation - https://angular.io/cli
Github Documentation - https://docs.github.com/en
How do I install Homebrew on Mac? - https://osxdaily.com/2018/03/07/how-install-homebrew-mac-os/
How do I install NodeJs on on mac? - https://www.webucator.com/how-to/how-install-nodejs-on-mac.cfm
How do I install Anuglar on mac? - https://www.zeolearn.com/magazine/setup-angular-mac

**Comment by oiricaud** [comment]
@linlin321 this will be your first task :)

**Comment by lincherryz** [comment]
is this the thread you are talking about??

**Comment by oiricaud** [comment]
si 😺

**Comment by lincherryz** [comment]
angular installation gives me an error. says library no longer supported. missing write access??

**Comment by oiricaud** [comment]
copy and paste the error here and use the `<>` icon on this github comment to paste your error code and i'll look it up and see what is up

**Comment by oiricaud** [comment]
run `history` on your terminal and paste it here

**Comment by oiricaud** [comment]
@linlin321 run step 4 & 5 for now :)

**Comment by lincherryz** [comment]
`ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/linpotato/.npm/_logs/2020-09-28T02_24_15_421Z-debug.log`

**Comment by oiricaud** [comment]
Run `cat /Users/linpotato/.npm/_logs/2020-09-28T02_24_15_421Z-debug.log` and paste the log here

**Comment by lincherryz** [comment]
` 4  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"\n
    5  RETURN
    6  brew install wget
    7  ls
    8  clear
    9  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"\n
   10  brew help
   11  brew help
   12  brew help [COMMAND]
   13  cd
   14  ls
   15  npm install -g @angular/cli
   16  ng help
   17  cd
   18  ls
   19  npm install -g @angular/cli`

**Comment by oiricaud** [comment]
What was the last command you ran on your terminal? You can check by typing `history` on your terminal

**Comment by lincherryz** [comment]
the log for the cat command is really long do you want me to paste the whole thing?

**Comment by lincherryz** [comment]
npm intall -g @angular/cli

**Comment by oiricaud** [comment]
Try this tutorial https://tecadmin.net/install-angular-on-macos/ and let me know how it goes

**Comment by oiricaud** [comment]
you can attach files on here too! so you can just attach that file :)

**Comment by oiricaud** [comment]
You can run this to open the directory and just drag and drop the log inside the directory `open /Users/linpotato/.npm/_logs`

**Comment by lincherryz** [comment]
i keep getting the same error for #4. i googled it and came across this, should i follow it or do you wanna see the error again first? https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by oiricaud** [comment]
Yeah try it let me know how it goes

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
